### PR TITLE
fix: ActionMenu proptypes

### LINKED ISSUE #1524: Warning for ActionMenu using placement props
There is a deprecation warning when using the placement
props for the ActionMenu component.

```
<ActionMenu placement /> is deprecated, use <ActionMenu popperOptions={{ placement }} /> instead
```

The problem is that there is defaultProps.placement which
means the warning is there even if the user has not used
the placement props.

Can you take a look @y-lhose ?

### PR DESCRIPTION
**Pull request by y-lohse**
Updates the proptypes of action menu and fixes #1524
.

### CODE REVIEW

**Review by JF-Cozy — APPROVED** [review]
LGTM 👍

**Review by Crash-- — APPROVED** [review]

File: test/testFromStyleguidist.js [hunk 1]
```diff
@@ -49,11 +49,12 @@ const testFromStyleguidist = (name, markdown, require) => {
         })
         done()
       }
-      codes.forEach(code => {
+      codes.forEach(async code => {
         const root = mount(
           <Preview code={code.content} evalInContext={evalInContext} />,
           options
         )
+        await sleep(100)
```
Comment (ptbrowne) [inline test/testFromStyleguidist.js:57]: Can you add a comment telling us why is this necessary ? I am a bit unconfortable to add this delay to all tests when it is necessary only for one. Is it not possible to specify the delay only for ActionMenu ?

Comment (y-lohse) [reply test/testFromStyleguidist.js:57]: Sorry, I wasn't done yet! Since the test seems more flaky on the CI than on my machine, I first wanted to confirm that the sleep *really* works, including on the CI.

But yes, I wouldn't like it to stay that way either. I haven't found a way to *not* use a timer at all, but running it only for components that need it as you suggest is a good idea, thanks 👍

Comment (ptbrowne) [reply test/testFromStyleguidist.js:57]: Have you understood why the test is flaky, checking the code in material ui ?

Comment (y-lohse) [reply test/testFromStyleguidist.js]: > Have you understood why the test is flaky, checking the code in material ui ?

The problem comes from popper-core, but no I haven't dug into the source to see what is going on. All I can say for sure is that the return value of `usePopper` changes multiples times, and it seems to come from popper-core and not react-popper itself.

**Comment by y-lohse** [comment]
Ok, the tests seem stable now, by adding a small delay on the ActionMenu test!

**Comment by ptbrowne** [comment]
Thanks 👍

**Review by ptbrowne — APPROVED** [review]
